# Place this file into config folder of your RailsRoot
api-key: 'f477fc44-1923-4157-9f20-f0feeb41a755'
development:
 enabled: false
production:
  enabled: true
staging:
  api-key: 'f477fc44-1923-4157-9f20-f0feeb41a755' # You can change if you have create different project
  enabled: true
